In [72]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import random as rand
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from collections import Counter
data_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label']
data = pd.read_csv('iris.data', 
                   names = data_names)

In [73]:
print(data.loc[0])

sepal_length            5.1
sepal_width             3.5
petal_length            1.4
petal_width             0.2
label           Iris-setosa
Name: 0, dtype: object


In [74]:
print(data.loc[0][0])

5.1


In [75]:
print(data.sepal_length[0])

5.1


In [76]:
print(data.loc[0].values)

[5.1 3.5 1.4 0.2 'Iris-setosa']


In [77]:
sub_data = data.loc[data['label'] != 'Iris-setosa', :]
y = sub_data['petal_length'].values
x = sub_data['sepal_length'].values
#array reshaped with 25 rows and 4 columns :  100 data 25*4 = 100
x = x.reshape(25, 4)
print(x)
for i in range(len(x)):
    print(i)

[[7.  6.4 6.9 5.5]
 [6.5 5.7 6.3 4.9]
 [6.6 5.2 5.  5.9]
 [6.  6.1 5.6 6.7]
 [5.6 5.8 6.2 5.6]
 [5.9 6.1 6.3 6.1]
 [6.4 6.6 6.8 6.7]
 [6.  5.7 5.5 5.5]
 [5.8 6.  5.4 6. ]
 [6.7 6.3 5.6 5.5]
 [5.5 6.1 5.8 5. ]
 [5.6 5.7 5.7 6.2]
 [5.1 5.7 6.3 5.8]
 [7.1 6.3 6.5 7.6]
 [4.9 7.3 6.7 7.2]
 [6.5 6.4 6.8 5.7]
 [5.8 6.4 6.5 7.7]
 [7.7 6.  6.9 5.6]
 [7.7 6.3 6.7 7.2]
 [6.2 6.1 6.4 7.2]
 [7.4 7.9 6.4 6.3]
 [6.1 7.7 6.3 6.4]
 [6.  6.9 6.7 6.9]
 [5.8 6.8 6.7 6.7]
 [6.3 6.5 6.2 5.9]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [78]:
#unknown row and 5 columns
x = x.reshape(-1, 5)
print(x)

[[7.  6.4 6.9 5.5 6.5]
 [5.7 6.3 4.9 6.6 5.2]
 [5.  5.9 6.  6.1 5.6]
 [6.7 5.6 5.8 6.2 5.6]
 [5.9 6.1 6.3 6.1 6.4]
 [6.6 6.8 6.7 6.  5.7]
 [5.5 5.5 5.8 6.  5.4]
 [6.  6.7 6.3 5.6 5.5]
 [5.5 6.1 5.8 5.  5.6]
 [5.7 5.7 6.2 5.1 5.7]
 [6.3 5.8 7.1 6.3 6.5]
 [7.6 4.9 7.3 6.7 7.2]
 [6.5 6.4 6.8 5.7 5.8]
 [6.4 6.5 7.7 7.7 6. ]
 [6.9 5.6 7.7 6.3 6.7]
 [7.2 6.2 6.1 6.4 7.2]
 [7.4 7.9 6.4 6.3 6.1]
 [7.7 6.3 6.4 6.  6.9]
 [6.7 6.9 5.8 6.8 6.7]
 [6.7 6.3 6.5 6.2 5.9]]


In [79]:
def addition(a,b):
    a += 5
    b += 10
    
    return x,y

a = 10
b = 15
a , b = addition(a,b)
print (a)
print(b)

[[7.  6.4 6.9 5.5 6.5]
 [5.7 6.3 4.9 6.6 5.2]
 [5.  5.9 6.  6.1 5.6]
 [6.7 5.6 5.8 6.2 5.6]
 [5.9 6.1 6.3 6.1 6.4]
 [6.6 6.8 6.7 6.  5.7]
 [5.5 5.5 5.8 6.  5.4]
 [6.  6.7 6.3 5.6 5.5]
 [5.5 6.1 5.8 5.  5.6]
 [5.7 5.7 6.2 5.1 5.7]
 [6.3 5.8 7.1 6.3 6.5]
 [7.6 4.9 7.3 6.7 7.2]
 [6.5 6.4 6.8 5.7 5.8]
 [6.4 6.5 7.7 7.7 6. ]
 [6.9 5.6 7.7 6.3 6.7]
 [7.2 6.2 6.1 6.4 7.2]
 [7.4 7.9 6.4 6.3 6.1]
 [7.7 6.3 6.4 6.  6.9]
 [6.7 6.9 5.8 6.8 6.7]
 [6.7 6.3 6.5 6.2 5.9]]
[4.7 4.5 4.9 4.  4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1
 4.5 3.9 4.8 4.  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5
 4.7 4.4 4.1 4.  4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6
 5.8 6.6 4.5 6.3 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9
 6.7 4.9 5.7 6.  4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4
 5.6 5.1 5.1 5.9 5.7 5.2 5.  5.2 5.4 5.1]


In [80]:
# Creates a list containing 5 lists, each of 8 items, all set to 0
w, h = 8, 5;
Matrix = [[0 for x in range(w)] for y in range(h)] 
print(Matrix[0][0])

0


In [81]:
# Use of break statement inside loop
for i in range (0,10):
    for val in "string":
        if val == "i":
            break
        print(val)

print("The end")

s
t
r
s
t
r
s
t
r
s
t
r
s
t
r
s
t
r
s
t
r
s
t
r
s
t
r
s
t
r
The end


In [ ]:
array = []
array.append(5)
array.append(10)
print(array[0])
print(array[1])

In [ ]:
for i in range (1, 10):
    print (i)

In [1]:
example = [0.,1.,2.]
if (example[1] == 1):
    print("it is 1")

it is 1
